INSERT INTO "bird" ("species_lt", "species_en", "species_latin")
VALUES
    ("Didžioji zylė", "Great Tit", "Parus major"),
    ("Mėlynoji zylė", "Eurasian Blue Tit", "Cyanistes caeruleus"),
    ("Pilkoji varna", "Hooded Crow", "Corvus cornix"),
    ("Didžioji antis", "Mallard", "Anas platyrhynchos"),
    ("Kėkštas", "Eurasian Jay", "Garrulus glandarius"),
    ("Karklažvirblis", "Eurasian Tree Sparrow", "Passer montanus"),
    ("Didysis margasis genys", "Great Spotted Woodpecker", "Dendrocopos major"),
    ("Šarka", "Eurasian Magpie", "Pica pica"),
    ("Juodasis strazdas", "Common Blackbird", "Turdus merula"),
    ("Smilginis strazdas", "Fieldfare", "Turdus pilaris"),
    ("Gulbė nebylė", "Mute Swan", "Cygnus olor"),
    ("Žaliukė", "European Greenfinch", "Chloris chloris"),
    ("Kranklys", "Northern Raven", "Corvus corax"),
    ("Paprastasis varnėnas", "Common Starlin", "Sturnus vulgaris"),
    ("Kuosa", "Western Jackdaw", "Coloeus monedula"),
    ("Geltonoji starta", "Yellowhammer", "Emberiza citrinella"),
    ("Naminis žvirblis", "House Sparrow", "Passer domesticus"),
    ("Kovas", "Rook", "Corvus frugilegus"),
    ("Juodagalvė sniegena", "Eurasian Bullfinch", "Pyrrhula pyrrhula"),
    ("Paprastoji pilkoji zylė", "Marsh Tit", "Poecile palustris"),
    ("Paprastasis kikilis", "Common Chaffinch", "Fringilla coelebs"),
    ("Bukutis", "Eurasian Nuthatch", "Sitta "),
    ("Paprastasis suopis", "Common Buzzard", "Buteo buteo"),
    ("Didysis dančiasnapis", "Common Merganser", "Mergus merganser"),
    ("Pilkoji gervė", "Common Crane", "Grus grus"),
    ("Rudagalvis kiras", "Black-headed Gull", "Chroicocephalus ridibundus"),
    ("Dagilis", "European Goldfinch", "Carduelis carduelis"),
    ("Baltoji kielė", "White Wagtail", "Motacilla alba"),
    ("Pilkasis garnys", "Grey Heron", "Ardea cinerea"),
    ("Klykuolė", "Common Goldeneye", "Bucephala clangula"),
    ("Naminis karvelis", "Rock Dove", "Columba livia"),
    ("Baltasis gandras", "White Stork", "Ciconia ciconia"),
    ("Laukys", "Eurasian Coot", "Fulica atra"),
    ("Keršulis", "Common Wood Pigeon", "Columba palumbus"),
    ("Gulbė giesmininkė", "Whooper Swan", "Cygnus cygnus"),
    ("Didysis baltasis garnys", "Great Egret", "Ardea alba"),
    ("Didysis kormoranas", "Great Cormorant", "Phalacrocorax carbo"),
    ("Liepsnelė", "European Robin", "Erithacus rubecula"),
    ("Ilgauodegė zylė", "Long-tailed Tit", "Aegithalos caudatus"),
    ("Svilikas", "Hawfinch", "Coccothraustes coccothraustes"),
    ("Alksninukas", "Eurasian Siskin", "Spinus spinus"),
    ("Paprastoji pempė", "Northern Lapwing", "Vanellus vanellus"),
    ("Jūrinis erelis", "White-tailed Eagle", "Haliaeetus albicilla"),
    ("Miškinis liputis", "Eurasian Treecreeper", "Certhia familiaris"),
    ("Kuoduotoji zylė", "European Crested Tit", "Lophophanes cristatus"),
    ("Paukštvanagis", "Eurasian Sparrowhawk", "Accipiter nisus"),
    ("Ausuotasis kragas", "Great Crested Grebe", "Podiceps cristatus"),
    ("Sidabrinis kiras", "European Herring Gull", "Larus argentatus"),
    ("Paprastasis nykštukas", "Goldcrest", "Regulus regulus"),
    ("Vidutinis margasis genys", "Middle Spotted Woodpecker", "Dendrocoptes medius"),
    ("Šelmeninė kregždė", "Barn Swallow", "Hirundo rustica"),
    ("Kurapka", "Grey Partridge", "Perdix perdix"),
    ("Dirvinis vieversys", "Eurasian Skylark", "Alauda arvensis"),
    ("Juodoji meleta", "Black Woodpecker", "Dryocopus martius"),
    ("Pietinis purplelis", "Eurasian Collared Dove", "Streptopelia decaocto"),
    ("Dūminė raudonuodegė", "Black Redstart", "Phoenicurus ochruros"),
    ("Strazdas giesmininkas", "Song Thrush", "Turdus philomelos"),
    ("Paprastasis čivylis", "Common Linnet", "Linaria cannabina"),
    ("Karietaitė", "Eurasian Wren", "Troglodytes troglodytes"),
    ("Nendrinė lingė", "Western Marsh Harrier", "Circus aeruginosus"),
    ("Langinė kregždė", "Common House Martin", "Delichon urbicum"),
    ("Plėšrioji medšarkė", "Great Grey Shrike", "Lanius excubitor"),
    ("Svirbelis", "Bohemian Waxwing", "Bombycilla garrulus"),
    ("Paprastoji raudonuodegė", "Common Redstart", "Phoenicurus phoenicurus"),
    ("Juodasis čiurlys", "Common Swift", "Apus apus"),
    ("Gegutė", "Common Cuckoo", "Cuculus canorus"),
    ("Paprastasis kiras", "Mew Gull", "Larus canus"),
    ("Pilkoji pečialinda", "Common Chiffchaff", "Phylloscopus collybita"),
    ("Juodoji zylė", "Coal Tit", "Periparus ater"),
    ("Kuoduotoji antis", "Tufted Duck", "Aythya fuligula"),
    ("Paprastoji medšarkė", "Red-backed Shrike", "Lanius collurio"),
    ("Margasparnė musinukė", "European Pied Flycatcher", "Ficedula hypoleuca"),
    ("Upinė žuvėdra", "Common Tern", "Sterna hirundo"),
    ("Tulžys", "Common Kingfisher", "Alcedo atthis"),
    ("Nendrinė starta", "Common Reed Bunting", "Emberiza schoeniclus"),
    ("Geltonoji kielė", "Western Yellow Wagtail", "Motacilla flava"),
    ("Paprastoji kiauliukė", "Whinchat", "Saxicola rubetra"),
    ("Eurazinė cyplė", "Eurasian Wigeon", "Mareca penelope"),
    ("Mažasis margasis genys", "Lesser Spotted Woodpecker", "Dryobates minor"),
    ("Baltakaktė žąsis", "Greater White-fronted Goose", "Anser albifrons"),
    ("Pilkoji musinukė", "Spotted Flycatcher", "Muscicapa striata"),
    ("Didžioji krakšlė", "Great Reed Warbler", "Acrocephalus arundinaceus"),
    ("Kukutis", "Eurasian Hoopoe", "Upupa epops"),
    ("Juodagalvė devynbalsė", "Eurasian Blackcap", "Sylvia atricapilla"),
    ("Žalioji pečialinda", "Wood Warbler", "Phylloscopus sibilatrix"),
    ("Perkūno oželis", "Common Snipe", "Gallinago gallinago"),
    ("Pilkoji žąsis", "Greylag Goose", "Anser anser"),
    ("Volungė", "Eurasian Golden Oriole", "Oriolus oriolus"),
    ("Ežerinė nendrinukė", "Sedge Warbler", "Acrocephalus schoenobaenus"),
    ("Naminė pelėda", "Tawny Owl", "Strix aluco"),
    ("Šiaurinė pilkoji zylė", "Willow Tit", "Poecile montanus"),
    ("Pilkoji devynbalsė", "Lesser Whitethroat", "Curruca curruca"),
    ("Šiaurinis kikilis", "Brambling", "Fringilla montifringilla"),
    ("Rytinė lakštingala", "Thrush Nightingale", "Luscinia luscinia"),
    ("Rudagalvė kryklė", "Eurasian Teal", "Anas crecca"),
    ("Rudoji devynbalsė", "Common Whitethroat", "Curruca communis"),
    ("Krantinis tilvikas", "Common Sandpiper", "Actitis hypoleucos"),
    ("Mažasis kragas", "Little Grebe", "Tachybaptus ruficollis"),
    ("Pilkoji meleta", "Grey-headed Woodpecker", "Picus canus"),
    ("Nendrinė vištelė", "Common Moorhen", "Gallinula chloropus");